const app=document.getElementById("app");
const BOOKS=Object.keys(CHAPTERS); let s={items:[],i:0,answers:[],score:0,sec:0,timer:null,title:""};
const PK="studymate-progress-v1", SEEN="studymate-seen-v1";
const bn=n=>String(n).replace(/\d/g,d=>"০১২৩৪৫৬৭৮৯"[d]);
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const getP=()=>{try{return JSON.parse(localStorage.getItem(PK))||{}}catch{return{}}};
const saveP=x=>localStorage.setItem(PK,JSON.stringify(x));
const getSeen=()=>{try{return JSON.parse(localStorage.getItem(SEEN))||{}}catch{return{}}};
const saveSeen=x=>localStorage.setItem(SEEN,JSON.stringify(x));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const fmt=x=>`${Math.floor(x/60)}:${String(Math.max(0,x%60)).padStart(2,"0")}`;
function clearT(){if(s.timer)clearInterval(s.timer);s.timer=null}
function pickFresh(pool,n,key){const seen=getSeen(),ids=seen[key]||[],fresh=pool.filter(q=>!ids.includes(q.id)),old=pool.filter(q=>ids.includes(q.id));let picked=shuffle(fresh).slice(0,n);if(picked.length<n)picked.push(...shuffle(old).slice(0,n-picked.length));seen[key]=[...new Set([...ids,...picked.map(q=>q.id)])].slice(-Math.max(2000,pool.length));saveSeen(seen);return picked}
function displayQ(q){const ct=q.options[q.correct],opts=shuffle(q.options),prefix=["","ভালোভাবে পড়ে উত্তর দাও—","ধারণাটি বুঝে উত্তর দাও—","একটু tricky করে ভাবো—","সবচেয়ে নির্ভুল উত্তরটি বেছে নাও—"][Math.floor(Math.random()*5)];return {...q,displayQuestion:prefix+q.question,options:opts,correct:opts.indexOf(ct)}}
function home(){clearT();app.innerHTML=`<section class="hero"><span class="pill">NO LOGIN • GITHUB READY</span><h1>StudyMate<br><span>পড়ো • অনুশীলন • জিতে যাও</span></h1><p>শুধু Biology, Chemistry, Physics ও BGS — সব chapter, hard MCQ, সংজ্ঞা, model test এবং local progress.</p><div class="stats"><div><b>৪</b><small>বিষয়</small></div><div><b>৫৫</b><small>অধ্যায়/অংশ</small></div><div><b>১২,০০০</b><small>original practice MCQ</small></div></div></section><section class="wrap"><div class="cards"><button onclick="books()">📚<b>সব অধ্যায়</b><small>৫৫টি chapter/section</small></button><button onclick="practice()">📝<b>শুধু MCQ</b><small>fresh প্রশ্ন আগে</small></button><button onclick="mock()">⏱<b>মডেল টেস্ট</b><small>mixed hard set</small></button><button onclick="definitions()">📖<b>সংজ্ঞা</b><small>দ্রুত revision</small></button><button onclick="progress()">📊<b>প্রগ্রেস</b><small>device-এ save</small></button></div></section>`}
function books(){clearT();app.innerHTML=`<section class="wrap"><button class="back" onclick="home()">← হোম</button><h2>সব অধ্যায়</h2>${BOOKS.map(b=>`<section class="subject"><h3>${esc(b)} <span>${bn(CHAPTERS[b].length)} অংশ</span></h3><div class="chaptergrid">${CHAPTERS[b].map((c,i)=>`<button class="chapter" onclick="chapter('${esc(b)}','${esc(c)}')"><b>${bn(i+1)}. ${esc(c)}</b><span>MCQ →</span></button>`).join('')}</div></section>`).join('')}</section>`}
function chapter(subject,ch){start(pickFresh(QUESTION_BANK.filter(q=>q.subject===subject&&q.chapter===ch),30,subject+'|'+ch),subject+' — '+ch)}
function practice(){clearT();app.innerHTML=`<section class="wrap"><button class="back" onclick="home()">← হোম</button><h2>শুধু MCQ</h2><div class="panel"><p>আগে দেখা প্রশ্ন এড়িয়ে fresh প্রশ্ন আগে আসবে। একই প্রশ্ন পরে এলে option order ও presentation বদলাতে পারে।</p><select id="sub">${BOOKS.map(b=>`<option>${esc(b)}</option>`).join('')}</select><select id="num"><option value="20">২০টি</option><option value="50">৫০টি</option><option value="100">১০০টি</option><option value="200">২০০টি</option></select><button class="primary" onclick="randomTest()">শুরু করো →</button></div></section>`}
function randomTest(){const b=document.getElementById('sub').value,n=+document.getElementById('num').value;start(pickFresh(QUESTION_BANK.filter(q=>q.subject===b),n,b),b)}
function mock(){start(pickFresh(QUESTION_BANK,50,'MODEL'),'মডেল টেস্ট')}
function start(items,title){clearT();s={items:shuffle(items).map(displayQ),i:0,answers:[],score:0,sec:Math.max(60,items.length*35),timer:null,title};renderQ();s.timer=setInterval(()=>{s.sec--;const t=document.getElementById('time');if(t)t.textContent=fmt(s.sec);if(s.sec<=0)finish(true)},1000)}
function renderQ(){const q=s.items[s.i],a=s.answers[s.i];app.innerHTML=`<section class="wrap quiz"><div class="quiztop"><button class="back" onclick="exitQuiz()">← বের হব</button><strong>⏱ <span id="time">${fmt(s.sec)}</span></strong></div><div class="bar"><span style="width:${s.i/s.items.length*100}%"></span></div><div class="meta"><span>${esc(q.subject)} • অধ্যায় ${bn(q.chapterNo)}</span><b>${bn(s.i+1)} / ${bn(s.items.length)}</b></div><article class="qbox"><span class="tag">${esc(q.difficulty)} • ধারণাভিত্তিক</span><h2>${esc(q.displayQuestion)}</h2><div class="opts">${q.options.map((o,i)=>`<button class="opt ${a!==undefined?(i===q.correct?'ok':i===a?'bad':'dim'):''}" ${a!==undefined?'disabled':''} onclick="choose(${i})"><i>${'ক খ গ ঘ'[i]}</i>${esc(o)}</button>`).join('')}</div>${a!==undefined?`<div class="explain"><b>${a===q.correct?'সঠিক উত্তর ✅':'ভুল উত্তর ❌'}</b><p>${esc(q.explanation)}</p></div><button class="primary" onclick="nextQ()">${s.i===s.items.length-1?'ফলাফল দেখো':'পরের প্রশ্ন →'}</button>`:''}</article></section>`}
function choose(i){if(s.answers[s.i]!==undefined)return;s.answers[s.i]=i;if(i===s.items[s.i].correct)s.score++;renderQ()}
function nextQ(){s.i===s.items.length-1?finish(false):(s.i++,renderQ())}
function finish(timeout){clearT();const pct=Math.round(s.score/s.items.length*100),p=getP(),x=p[s.title]||{best:0,attempts:0};x.attempts++;x.best=Math.max(x.best,pct);p[s.title]=x;saveP(p);app.innerHTML=`<section class="result"><div class="resultcard"><span class="pill">${timeout?'সময় শেষ':'শেষ'}</span><div class="circle">${bn(pct)}%</div><h2>${pct>=90?'দারুণ!':pct>=70?'খুব ভালো!':pct>=50?'আরও অনুশীলন করো':'আবার চেষ্টা করো!'}</h2><p>${bn(s.items.length)}টির মধ্যে <b>${bn(s.score)}</b>টি সঠিক।</p><button class="primary" onclick="start(s.items,s.title)">আবার দাও</button> <button class="ghost" onclick="home()">হোম</button></div></section>`}
function definitions(){clearT();app.innerHTML=`<section class="wrap"><button class="back" onclick="home()">← হোম</button><h2>সংজ্ঞা ও ধারণা</h2><div class="defgrid">${DEFINITIONS.map(d=>`<article class="definition"><span class="tag">${esc(d.subject)}</span><h3>${esc(d.term)}</h3><p>${esc(d.definition)}</p></article>`).join('')}</div></section>`}
function progress(){clearT();const p=getP(),k=Object.keys(p),v=Object.values(p);app.innerHTML=`<section class="wrap"><button class="back" onclick="home()">← হোম</button><h2>তোমার প্রগ্রেস</h2><div class="progresscards"><div><b>${bn(k.length)}</b><small>section</small></div><div><b>${bn(v.reduce((a,x)=>a+x.attempts,0))}</b><small>attempt</small></div><div><b>${bn(k.length?Math.round(v.reduce((a,x)=>a+x.best,0)/k.length):0)}%</b><small>average best</small></div></div><div class="plist">${k.length?k.map(x=>`<div><b>${esc(x)}</b><span>${bn(p[x].best)}% • ${bn(p[x].attempts)} বার</span></div>`).join(''):'<div class="empty">এখনও কোনো test দেওয়া হয়নি।</div>'}</div><button class="danger" onclick="resetProgress()">সব progress মুছুন</button></section>`}
function resetProgress(){if(confirm('সব progress মুছে ফেলবে?')){localStorage.removeItem(PK);localStorage.removeItem(SEEN);progress()}}
function exitQuiz(){if(confirm('এই test ছেড়ে যাবে?')){clearT();home()}}
function toggleTheme(){const d=document.documentElement.classList.toggle('dark');localStorage.setItem('studymate-theme',d?'dark':'light');document.getElementById('theme').textContent=d?'☀':'☾'}
if(localStorage.getItem('studymate-theme')==='dark')document.documentElement.classList.add('dark');home();