const app=document.getElementById('app');
const BOOKS=Object.keys(CHAPTERS); const PK='studymate-progress-v5'; const SEEN='studymate-seen-v5';
let state={items:[],index:0,answers:[],score:0,title:'',subject:''};
const bn=n=>String(n).replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[d]);
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const load=k=>{try{return JSON.parse(localStorage.getItem(k))||{}}catch{return{}}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const shuffle=a=>{let x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
function pick(pool,n,key){const seen=load(SEEN),old=new Set(seen[key]||[]);const fresh=pool.filter(q=>!old.has(q.id));let chosen=shuffle(fresh).slice(0,n);if(chosen.length<n)chosen=chosen.concat(shuffle(pool.filter(q=>old.has(q.id))).slice(0,n-chosen.length));seen[key]=[...new Set([...(seen[key]||[]),...chosen.map(q=>q.id)])].slice(-Math.max(pool.length,500));save(SEEN,seen);return chosen}
function present(q){const natural=[q.question,q.question.replace('কোনটি?','কোনটি সঠিক?'),q.question.replace('কী?','কী—সঠিক উত্তরটি নির্বাচন করো।'),q.question.replace('কোনটি?','এর সঠিক উত্তর কোনটি?')];const question=natural[Math.floor(Math.random()*natural.length)];const correctText=q.options[q.correct];const options=shuffle(q.options);return {...q,question,options,correct:options.indexOf(correctText)}}
function home(){app.innerHTML=`<section class="hero"><span class="pill">STUDYMATE</span><h1>পড়ো। অনুশীলন করো।<br><span>নিজেকে যাচাই করো।</span></h1><p>জীববিজ্ঞান, রসায়ন, পদার্থবিজ্ঞান ও বাংলাদেশ ও বিশ্বপরিচয়।</p><div class="stats"><div><b>৪</b><small>বিষয়</small></div><div><b>৫৬</b><small>অধ্যায়</small></div><div><b>১০,০০০+</b><small>MCQ presentations</small></div></div></section><section class="wrap"><div class="home-grid"><button class="home-card" onclick="books()">📚<b>সব অধ্যায়</b><small>অধ্যায় ধরে অনুশীলন</small></button><button class="home-card" onclick="practice()">📝<b>শুধু MCQ</b><small>সরাসরি প্রশ্ন</small></button><button class="home-card" onclick="modelSetup()">🎯<b>মডেল টেস্ট</b><small>আগে বিষয় বেছে নাও</small></button><button class="home-card" onclick="definitions()">📖<b>সংজ্ঞা</b><small>দ্রুত revision</small></button><button class="home-card" onclick="progress()">📊<b>প্রগ্রেস</b><small>সেরা স্কোর</small></button></div></section>`}
function books(){app.innerHTML=`<section class="wrap"><button class="back" onclick="home()">← হোম</button><h2>সব অধ্যায়</h2>${BOOKS.map(s=>`<section class="subject-block"><div class="subject-title"><h3>${esc(s)}</h3><span>${bn(CHAPTERS[s].length)} অধ্যায়</span></div><div class="chapter-grid">${CHAPTERS[s].map((c,i)=>`<button class="chapter-card" onclick="chapterTest('${esc(s)}','${esc(c)}')"><b>${bn(i+1)}. ${esc(c)}</b><span>MCQ →</span></button>`).join('')}</div></section>`).join('')}</section>`}
function chapterTest(subject,chapter){const pool=QUESTION_BANK.filter(q=>q.subject===subject&&q.chapter===chapter);startQuiz(pick(pool,Math.min(30,pool.length),subject+'|'+chapter),subject+' — '+chapter,subject)}
function practice(){app.innerHTML=`<section class="wrap"><button class="back" onclick="home()">← হোম</button><h2>শুধু MCQ</h2><div class="setup-card"><label>বিষয়</label><select id="practiceSubject">${BOOKS.map(s=>`<option>${esc(s)}</option>`).join('')}</select><label>প্রশ্ন</label><select id="practiceCount"><option value="20">২০টি</option><option value="50">৫০টি</option><option value="100">১০০টি</option></select><button class="primary wide" onclick="startPractice()">MCQ শুরু</button></div></section>`}
function startPractice(){const s=document.getElementById('practiceSubject').value,n=+document.getElementById('practiceCount').value;startQuiz(pick(QUESTION_BANK.filter(q=>q.subject===s),n,s),s,s)}
function modelSetup(){app.innerHTML=`<section class="wrap"><button class="back" onclick="home()">← হোম</button><h2>মডেল টেস্ট</h2><div class="model-grid">${BOOKS.map(s=>`<button class="model-subject" onclick="modelSubject('${esc(s)}')"><b>${esc(s)}</b><span>এই বিষয়ের test →</span></button>`).join('')}<button class="model-subject mixed" onclick="modelMixed()"><b>সব বিষয়</b><span>Mixed test →</span></button></div></section>`}
function modelSubject(subject){app.innerHTML=`<section class="wrap"><button class="back" onclick="modelSetup()">← বিষয়</button><h2>${esc(subject)}</h2><div class="setup-card"><label>প্রশ্ন</label><select id="modelCount"><option>25</option><option selected>50</option><option>100</option></select><button class="primary wide" onclick="startModel('${esc(subject)}')">মডেল টেস্ট শুরু</button></div></section>`}
function startModel(subject){const n=+document.getElementById('modelCount').value;startQuiz(pick(QUESTION_BANK.filter(q=>q.subject===subject),n,'MODEL|'+subject),subject+' — মডেল টেস্ট',subject)}
function modelMixed(){app.innerHTML=`<section class="wrap"><button class="back" onclick="modelSetup()">← মডেল</button><h2>সব বিষয় — Mixed</h2><div class="setup-card"><label>প্রশ্ন</label><select id="mixedCount"><option>25</option><option selected>50</option><option>100</option></select><button class="primary wide" onclick="startMixed()">মডেল টেস্ট শুরু</button></div></section>`}
function startMixed(){const n=+document.getElementById('mixedCount').value;startQuiz(pick(QUESTION_BANK,n,'MODEL|MIXED'),'Mixed Model Test','সব বিষয়')}
function startQuiz(items,title,subject){state={items:shuffle(items).map(present),index:0,answers:[],score:0,title,subject};renderQuestion()}
function renderQuestion(){const q=state.items[state.index],a=state.answers[state.index];app.innerHTML=`<section class="wrap quiz"><div class="quiz-head"><button class="back" onclick="exitQuiz()">← বের হব</button><span class="question-number">${bn(state.index+1)} / ${bn(state.items.length)}</span></div><div class="progress-line"><span style="width:${(state.index+1)/state.items.length*100}%"></span></div><article class="question-card"><div class="question-meta">${esc(q.subject)} · ${esc(q.chapter)}</div><h2>${esc(q.question)}</h2><div class="options">${q.options.map((o,i)=>`<button class="option ${a!==undefined?(i===q.correct?'correct':i===a?'wrong':'dim'):''}" ${a!==undefined?'disabled':''} onclick="answer(${i})"><span class="letter">${['ক','খ','গ','ঘ'][i]}</span><span class="option-text">${esc(o)}</span></button>`).join('')}</div>${a!==undefined?`<div class="answer-box ${a===q.correct?'answer-good':'answer-bad'}"><b>${a===q.correct?'সঠিক উত্তর':'ভুল উত্তর'}</b><p>${esc(q.explanation)}</p></div><button class="primary next-button" onclick="nextQuestion()">${state.index===state.items.length-1?'ফলাফল':'পরের প্রশ্ন'}</button>`:''}</article></section>`}
function answer(i){if(state.answers[state.index]!==undefined)return;state.answers[state.index]=i;if(i===state.items[state.index].correct)state.score++;renderQuestion()}
function nextQuestion(){if(state.index===state.items.length-1){finish();return}state.index++;renderQuestion()}
function finish(){const total=state.items.length,pct=Math.round(state.score/total*100),p=load(PK),x=p[state.title]||{best:0,attempts:0};x.best=Math.max(x.best,pct);x.attempts++;p[state.title]=x;save(PK,p);app.innerHTML=`<section class="result"><div class="result-card"><span class="pill">শেষ</span><div class="score-circle">${bn(pct)}%</div><h2>${bn(state.score)} / ${bn(total)}</h2><p>সঠিক: ${bn(state.score)}</p><div class="result-actions"><button class="primary" onclick="startQuiz(state.items,state.title,state.subject)">আবার</button><button class="ghost" onclick="home()">হোম</button></div></div></section>`}
function exitQuiz(){if(confirm('এই test ছেড়ে যাবে?'))home()}
function definitions(){app.innerHTML=`<section class="wrap"><button class="back" onclick="home()">← হোম</button><h2>সংজ্ঞা ও ধারণা</h2><div class="definition-grid">${DEFINITIONS.map(d=>`<article class="definition-card"><span class="tag">${esc(d.subject)}</span><h3>${esc(d.term)}</h3><p>${esc(d.definition)}</p></article>`).join('')}</div></section>`}
function progress(){const p=load(PK),keys=Object.keys(p),v=Object.values(p);app.innerHTML=`<section class="wrap"><button class="back" onclick="home()">← হোম</button><h2>প্রগ্রেস</h2><div class="progress-cards"><div><b>${bn(keys.length)}</b><small>টেস্ট</small></div><div><b>${bn(v.reduce((a,x)=>a+x.attempts,0))}</b><small>attempt</small></div><div><b>${bn(keys.length?Math.round(v.reduce((a,x)=>a+x.best,0)/keys.length):0)}%</b><small>সেরা গড়</small></div></div><div class="progress-list">${keys.length?keys.map(k=>`<div><b>${esc(k)}</b><span>${bn(p[k].best)}% · ${bn(p[k].attempts)} বার</span></div>`).join(''):`<div class="empty">এখনও কোনো test দেওয়া হয়নি।</div>`}</div><button class="danger" onclick="resetAll()">সব মুছুন</button></section>`}
function resetAll(){if(confirm('সব progress ও question history মুছবে?')){localStorage.removeItem(PK);localStorage.removeItem(SEEN);progress()}}
function toggleTheme(){const d=document.documentElement.classList.toggle('dark');localStorage.setItem('studymate-theme',d?'dark':'light');document.getElementById('theme').textContent=d?'☀':'☾'}
if(localStorage.getItem('studymate-theme')==='dark')document.documentElement.classList.add('dark');home();